### ISSUE TITLE
provide alternate means of registration

### ISSUE THREAD

**Issue by afeld** [18F/chat#15]
Since Google Forms are blocked at some agencies, we should provide an alternate registration path. Maybe as simple as "Can't see the form? Email <whatever>."

**Comment by its-a-lisa-at-work** [comment]
@afeld is this something that we're doing or that we're watching? If we're doing, could we move over to the TTS Tech Portfolio repo for better issue tracking?

**Comment by its-a-lisa-at-work** [comment]
@afeld should this stay on our board? If so, are we the owners of this repo? Otherwise, I would maybe transfer this to our repo unless it needs to stay in this repo

**Comment by afeld** [comment]
> should this stay on our board?

Yep.

> are we the owners of this repo?

[Yep.](https://github.com/18F/tts-tech-portfolio/blob/master/how_we_work/github.md)

**Comment by afeld** [comment]
> is this something that we're doing or that we're watching?

Would make a tidy little microrequest, or experiment for someone playing around with HTML.

**Comment by its-a-lisa-at-work** [comment]
Hmm, I think this can be done in SmartSheets and don't believe it is typically blocked. Who would be the folks that need to see the requests that come in? I could do a quick MVP for them to see if that would suit their needs. 

Otherwise, I'm happy to tinker with some HTML as a fun side project, but thinking through the SaaS -> PaaS -> IaaS decision matrix we chatted about earlier.

**Comment by afeld** [comment]
Open to that, but it would be a much larger change than what I was going for in this issue.

**Comment by afeld** [comment]
Not planning to tackle in next six months; closing.
